### ISSUE TITLE
Add flag for DisableFastUpToDateCheck in VS builds

### ISSUE THREAD

**Issue by noct** [bkaradzic/GENie#438]
VS by default does it's own check for up-to-date builds which prevents the pre-build step from running. It's desirable to disable this if the pre-build step does code generation which affects the build.

Happy to provide a PR for this (with some advice on what to name the flag).

**Comment by bkaradzic** [comment]
Is this per file flag?

**Comment by noct** [comment]
Per project

**Comment by bkaradzic** [comment]
So all prebuild steps will be done before dependency check?

Also how you plan to support this with Make?

**Comment by noct** [comment]
Correct. As far as I'm aware this is already the behaviour; my gmake builds
already run pre-build steps for every invocation of make.

**Comment by bkaradzic** [comment]
It seems it could be set per file:
https://stackoverflow.com/a/49639051

```xml
<PropertyGroup>
    <PostBuildEvent>...
    <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
</PropertyGroup>
```

**Comment by noct** [comment]
Possibly, though I'm not sure what the utility would be or how that would
differ from a per-project setting in terms of how VS behaves (does it skip
MSBuild or not).

In my case I'm generating code as part of a pre-build step, and it would be
useful to have that work on Windows+VS as it does on Linux+gmake, but it
seems more reasonable to leave as an option for projects who'd prefer
faster no-op builds.

**Comment by drewnoakes** [comment]
I'm a dev on the VS project system team and came across this issue while searching for places where people use `DisableFastUpToDateCheck`.

> It's desirable to disable this if the pre-build step does code generation which affects the build.

The fast up-to-date check can save you a lot of time during build, so it's generally a bad idea to turn it off.

If you have generation that is not running during build because the project is considered up-to-date then the best fix is to expose the source files to that generation as `UpToDateCheckInput` items. In that way, the project system can detect when those inputs change and schedule builds correctly.

I know this is an old discussion, but it ranks highly on search results for this feature so even if it doesn't apply to this project, this comment may help others.
